# python
name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: curl -fsS https://dotenvx.sh/ | sh
    - run: dotenvx run -- python build.py
      env:
        DOTENV_KEY: ${{ secrets.DOTENV_KEY }}
